version: "3.3"
services:
  loopback-react:
    container_name: loopback-react
    build:
      context: .
      dockerfile: Dockerfile.backend 
    ports:
      - "3000:3000" 
    volumes:
      - ./loopback:/app/loopback
    depends_on:
      - database
    networks:
      - loopback_network

  coreui-react:
    container_name: coreui-react
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4000:3000"
    volumes:
      - ./coreui-react:/app/coreui-react
    networks:
      - loopback_network

  database:
    image: mysql:latest
    container_name: database
    ports:
      - "3306:3306" 
    env_file:
      - .env
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - loopback_network

networks:
  loopback_network:
